# Generated by Django 4.2.5 on 2023-09-20 14:15

import charges.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
            ],
            options={
                "ordering": ("-is_active", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("is_online", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Payment Mode",
                "verbose_name_plural": "Payment Modes",
            },
        ),
        migrations.CreateModel(
            name="ParkingSpotRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("valid_from", models.TimeField(db_index=True, null=True)),
                ("valid_till", models.TimeField(db_index=True, null=True)),
                (
                    "is_parking_allowed",
                    models.BooleanField(db_index=True, default=True),
                ),
                ("days", models.ManyToManyField(db_index=True, to="main.days")),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.floorplan",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        default=charges.models.Offer.get_default_pk,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charges.offer",
                    ),
                ),
                (
                    "vehicle_types",
                    models.ManyToManyField(db_index=True, to="inventory.vehicletype"),
                ),
            ],
            options={
                "verbose_name": "Parking Spot Rate",
                "verbose_name_plural": "Parking Spot Rates",
            },
        ),
        migrations.CreateModel(
            name="ParkingSpotHourlyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("fixed_rate", models.FloatField(db_index=True, default=0)),
                ("max_rate", models.FloatField(db_index=True, default=0)),
                ("hourly_rate", models.FloatField(db_index=True, default=0)),
                (
                    "valid_from",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Value between 0 and 24",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "valid_till",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Value between 0 and 24",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "parking_spot_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charges.parkingspotrate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Spot Hourly Rate",
                "verbose_name_plural": "Parking Spot Hourly Rates",
            },
        ),
    ]
