# Generated by Django 4.2.5 on 2023-09-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspotrate",
            name="valid_till",
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
