# Generated by Django 4.2.5 on 2023-09-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0002_alter_parkingspotrate_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspotrate",
            name="valid_till",
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
