# Generated by Django 4.2.5 on 2023-09-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0003_alter_parkingspotrate_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspothourlyrate",
            name="parking_spot_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parking_spot_hourly_rate",
                to="charges.parkingspotrate",
            ),
        ),
    ]
