# Generated by Django 4.2.5 on 2023-09-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_floorplan_options"),
        ("charges", "0004_alter_parkingspothourlyrate_parking_spot_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingspotrate",
            name="vehicle_types",
        ),
        migrations.AddField(
            model_name="parkingspotrate",
            name="vehicle_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parking_spot_rate_vehicle",
                to="inventory.vehicletype",
            ),
        ),
    ]
