# Generated by Django 4.2.5 on 2023-09-30 14:03

from django.db import migrations, models
import inventory.models.helpers


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0006_alter_parkingspotrate_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspotrate",
            name="valid_from",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=inventory.models.helpers.default_start_time,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="parkingspotrate",
            name="valid_till",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=inventory.models.helpers.default_end_time,
                null=True,
            ),
        ),
    ]
