# Generated by Django 4.2.5 on 2023-09-30 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0007_alter_parkingspotrate_valid_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspotrate",
            name="night_charge_fixed",
            field=models.FloatField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="parkingspotrate",
            name="night_charge_per_hour",
            field=models.FloatField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="parkingspothourlyrate",
            name="fixed_rate",
            field=models.FloatField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="parkingspothourlyrate",
            name="hourly_rate",
            field=models.FloatField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="parkingspothourlyrate",
            name="max_rate",
            field=models.FloatField(
                db_index=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
