default:
  image: ubuntu:20.04

  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get -y --no-install-recommends install tzdata
    - cp /usr/share/zoneinfo/Australia/Brisbane /etc/localtime
    - apt -y update
    - apt -y install apt-utils
    - apt -y install net-tools python3.9 python3-pip
    - apt -y upgrade
    - pip3 install -r requirements.txt

migrations:
  stage: build
  script:
    - mv .env.sample .env
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^v.*/


django-tests:
  stage: test
  script:
    - python3 manage.py test
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^v.*/
