# Generated by Django 4.2.5 on 2023-09-27 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprovider",
            name="poc",
        ),
    ]
