# Generated by Django 4.2.5 on 2023-09-27 18:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_remove_serviceprovider_poc"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="phone_num",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, db_index=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="serviceprovider",
            name="name",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
