# Generated by Django 4.2.5 on 2023-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0003_serviceprovider_phone_num_alter_serviceprovider_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="name",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
