# Generated by Django 4.2.5 on 2023-09-27 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0004_alter_serviceprovider_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="serviceprovider",
            unique_together={("name", "phone_num")},
        ),
    ]
