# Generated by Django 4.2.5 on 2023-09-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0002_remove_serviceprovider_poc"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="service_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.serviceprovider",
            ),
        ),
    ]
