# Generated by Django 4.2.5 on 2023-09-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Days",
            fields=[
                (
                    "day",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.IntegerField(db_index=True, default=0)),
                ("master_order", models.IntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Day",
                "verbose_name_plural": "Days",
                "ordering": ("order", "day"),
            },
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("name", models.CharField(help_text="Some test field", max_length=127)),
            ],
            options={
                "verbose_name": "Test Model",
                "verbose_name_plural": "Test Model",
                "ordering": ("-is_active", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "title",
                    models.CharField(help_text="Title for the site", max_length=127),
                ),
                (
                    "starting_of_the_week",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.days",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ("-created_at",),
            },
        ),
    ]
