# Generated by Django 4.2.5 on 2023-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days",
            name="master_order",
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="days",
            name="order",
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
    ]
