# Generated by Django 4.2.5 on 2023-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_days_master_order_alter_days_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="base_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
