# Generated by Django 4.2.5 on 2023-10-02 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_settings_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_1",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_1_threshold",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_2",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_2_threshold",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_3",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
