# Generated by Django 4.2.5 on 2023-10-03 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_settings_occupancy_level_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_1_color_primary",
            field=models.CharField(
                default="#CCFFCC",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_1_color_secondary",
            field=models.CharField(
                default="#99FF99",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_2_color_primary",
            field=models.CharField(
                default="#FFFFCC",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_2_color_secondary",
            field=models.CharField(
                default="#FFFF99",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_3_color_primary",
            field=models.CharField(
                default="#FFCCCC",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="occupancy_level_3_color_secondary",
            field=models.CharField(
                default="#FF9999",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#(?:[0-9a-fA-F]{3}){1,2}$", "Invalid hex color."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="occupancy_level_1",
            field=models.CharField(
                blank=True,
                help_text="This level represents low occupancy.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="occupancy_level_2",
            field=models.CharField(
                blank=True,
                help_text="This level represents medium occupancy.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="occupancy_level_3",
            field=models.CharField(
                blank=True,
                help_text="This level represents high occupancy.",
                max_length=16,
                null=True,
            ),
        ),
    ]
