# Generated by Django 4.2.5 on 2023-09-20 14:15

import cropperjs.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "floor_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=8, null=True
                    ),
                ),
                (
                    "floor_name_long",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
                ("floor_num", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "num_rows",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "num_columns",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_slots",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_floors",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
                "unique_together": {("location", "floor_name")},
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "logo",
                    cropperjs.models.CropperImageField(
                        aspectratio="1.0",
                        blank=True,
                        dimensions=(256, 256),
                        help_text="Vehicle Type Image",
                        null=True,
                        upload_to="",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_active", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingSpotAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("total", models.PositiveIntegerField(db_index=True, default=0)),
                ("available", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_parking_availability",
                        to="inventory.floorplan",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Spot Availability",
                "verbose_name_plural": "Parking Spot Availabilities",
                "unique_together": {("floor", "vehicle_type")},
            },
        ),
        migrations.CreateModel(
            name="ParkingSpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("spot_code", models.CharField(db_index=True, max_length=8)),
                ("is_elevated", models.BooleanField(db_index=True, default=False)),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                (
                    "row_num",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "column_num",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_spot_floor",
                        to="inventory.floorplan",
                    ),
                ),
                (
                    "vehicle_types",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="spot_vehicle_types",
                        to="inventory.vehicletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parking Spot",
                "verbose_name_plural": "Parking Spots",
                "unique_together": {("floor", "spot_code")},
            },
        ),
    ]
