# Generated by Django 4.2.5 on 2023-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="gate_location",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="gate_num",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="has_toilet",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="is_divyang_friendly",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="is_parking_available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="is_parking_paid",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
