# Generated by Django 4.2.5 on 2023-09-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_floorplan_gate_location_floorplan_gate_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="is_elevated",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
