# Generated by Django 4.2.5 on 2023-09-20 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_floorplan_is_elevated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floorplan",
            options={
                "ordering": ("location", "floor_name", "-created_at"),
                "verbose_name": "Floor Plan",
                "verbose_name_plural": "Floor Plans",
            },
        ),
    ]
