# Generated by Django 4.2.5 on 2023-09-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_floorplan_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="full_name",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
