# Generated by Django 4.2.5 on 2023-09-25 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_vehicletype_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicletype",
            name="full_name",
        ),
    ]
