# Generated by Django 4.2.5 on 2023-09-26 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_remove_vehicletype_full_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicletype",
            old_name="logo",
            new_name="logo_image",
        ),
    ]
