# Generated by Django 4.2.5 on 2023-09-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_rename_logo_vehicletype_logo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletype",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
