# Generated by Django 4.2.5 on 2023-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_vehicletype_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicletype",
            name="logo",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
