# Generated by Django 4.2.5 on 2023-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_parkingspotavailability_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorplan",
            name="floor_name",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="floorplan",
            name="gate_location",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
