# Generated by Django 4.2.5 on 2023-09-30 13:52

from django.db import migrations, models
import inventory.models.helpers


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_floorplan_floor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="valid_from",
            field=models.TimeField(
                db_index=True,
                default=inventory.models.helpers.default_start_time,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="valid_till",
            field=models.TimeField(
                db_index=True,
                default=inventory.models.helpers.default_end_time,
                null=True,
            ),
        ),
    ]
