# Generated by Django 4.2.5 on 2023-10-01 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_floorplanprediction_floorplanpredictionvehiclewise"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floorplanprediction",
            options={
                "ordering": ("day", "time", "created_at"),
                "verbose_name": "Floor Plan Prediction",
                "verbose_name_plural": "Floor Plan Predictions",
            },
        ),
        migrations.AlterModelOptions(
            name="floorplanpredictionvehiclewise",
            options={
                "ordering": ("vehicle_type", "created_at"),
                "verbose_name": "Vehicle-Type Floor Plan Prediction",
                "verbose_name_plural": "Vehicle-Type Floor Plan Predictions",
            },
        ),
    ]
