# Generated by Django 4.2.5 on 2024-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_floorplanprediction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
