# Generated by Django 4.2.5 on 2023-09-20 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordinate",
                "verbose_name_plural": "Coordinates",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("name", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locations.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "ordering": ["name"],
                "unique_together": {("country", "name")},
            },
        ),
        migrations.CreateModel(
            name="PinCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=64)),
                ("city", models.CharField(max_length=64)),
                (
                    "code",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(100000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "coordinates_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="locations.coordinates",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Created date & time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last Updated date & time"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether is active or not?",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("name", models.CharField(db_index=True, max_length=256)),
                ("address", models.CharField(blank=True, max_length=1000)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Metro Station"),
                            (2, "Bus Depot"),
                            (3, "Mall"),
                            (4, "Office"),
                            (5, "Residential Area"),
                        ],
                        db_index=True,
                        default=2,
                    ),
                ),
                (
                    "is_parking_available",
                    models.BooleanField(db_index=True, default=True),
                ),
                (
                    "num_gates",
                    models.PositiveIntegerField(
                        blank=True, db_index=True, default=0, null=True
                    ),
                ),
                ("num_floors", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("is_underground", models.BooleanField(db_index=True, default=False)),
                ("is_junction", models.BooleanField(db_index=True, default=False)),
                (
                    "has_electric_charger",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "electric_charger_capacity",
                    models.FloatField(db_index=True, default=0),
                ),
                (
                    "num_electric_charger",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="locations.pincode",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="providers.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
            bases=("locations.coordinates", models.Model),
        ),
    ]
