# Generated by Django 4.2.5 on 2023-09-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charges", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="payment_mode",
            field=models.ManyToManyField(
                blank=True, db_index=True, to="charges.paymentmode"
            ),
        ),
    ]
