# Generated by Django 4.2.5 on 2023-09-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_location_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("code", "area")},
        ),
    ]
